## Partie 1 Traitement de données

In [1]:
import pandas as pd 
import numpy as np
import csv

## 1. Importation des données

In [2]:
ressources = pd.read_csv("ressources.csv",sep=",",decimal=",")
temps = pd.read_csv("temps.csv",sep= ",",decimal=",")

In [3]:
dossier =pd.read_csv("dossier.csv",sep=",",encoding="latin1", quoting=csv.QUOTE_MINIMAL)

Il y a eu des soucis d'importations du dataframe dossier, il nous a fallu utiliser une méthode d'importation plus robuste

In [4]:
# Parseur personnalisé pour recréer le DataFrame dossier.csv from scratch
import csv
from io import StringIO

def parse_dossier_csv(file_path):
    rows = []
    with open(file_path, 'r', encoding='latin1') as f:
        reader = csv.reader(f, quoting=csv.QUOTE_ALL)
        for row in reader:
            # row est ['ligne entière'], parser la ligne entière
            line = row[0]
            # Enlever les guillemets externes
            if line.startswith('"') and line.endswith('"'):
                line = line[1:-1]
            # Maintenant parser avec csv
            sub_reader = csv.reader(StringIO(line), delimiter=',', quotechar='"', doublequote=True)
            parsed_row = next(sub_reader)
            rows.append(parsed_row)
    
    # La première ligne est l'en-tête
    header = rows[0]
    data = rows[1:]
    return pd.DataFrame(data, columns=header)

# Utiliser le parseur
dossier = parse_dossier_csv("dossier.csv")
print("DataFrame recréé from scratch")
# Affichage des dimensions de chaque base
print("Dimensions de df_dossier :", dossier.shape)
print("Dimensions de df_ressources :", ressources.shape)
print("Dimensions de df_temps :", temps.shape)

DataFrame recréé from scratch
Dimensions de df_dossier : (101234, 17)
Dimensions de df_ressources : (389353, 9)
Dimensions de df_temps : (431598, 5)

In [5]:
dossier.head()

,Numero_dossier_ID,Client,Formule,date.ouverture,heure.ouverture,Matricule.de.traitement,Cause.intervention,date.de.survenance,Type.d.energie,Outil.d.assistance,Assistance.ou.Administratif,TOP.D.R,TOP.VR,TOP.Rappat.valide,TOP.Poursuite,TOP.Recup,TOP.Autres.Garanties
0,7494402,C5,F99,2021/02/11,10:38:00,326,Panne mécanique,2021/02/11,Diesel,MCS,Assistance,1,0,0,0,0,0
1,7569082,C4,F14,2022/07/12,18:40:00,1164,Panne mécanique,2022/07/12,Essence,MCS,???,1,0,0,0,0,0
2,8111190,C0,F1,2021/01/08,12:32:00,1337,Panne mécanique,2021/01/08,Essence,MCS,Assistance,1,1,0,0,0,0
3,5630809,C7,F72,2021/11/08,19:46:00,1322,Panne mécanique,2021/11/08,Essence,MCS,Assistance,1,0,0,0,0,0
4,8179409,C4,F4,2021/08/11,18:12:00,2306,Panne mécanique,2021/08/11,Essence,Higgins,???,1,0,0,0,0,0

In [6]:
dossier.info()

<class 'pandas.DataFrame'>
RangeIndex: 101234 entries, 0 to 101233
Data columns (total 17 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Numero_dossier_ID            101234 non-null  str
 1   Client                       101234 non-null  str
 2   Formule                      101234 non-null  str
 3   date.ouverture               101234 non-null  str
 4   heure.ouverture              101234 non-null  str
 5   Matricule.de.traitement      101234 non-null  str
 6   Cause.intervention           101234 non-null  str
 7   date.de.survenance           101234 non-null  str
 8   Type.d.energie               101234 non-null  str
 9   Outil.d.assistance           101234 non-null  str
 10  Assistance.ou.Administratif  101234 non-null  str
 11  TOP.D.R                      101234 non-null  str
 12  TOP.VR                       101234 non-null  str
 13  TOP.Rappat.valide            101234 non-null  str
 14  TOP.Poursuite                101234 non-null  str
 15  TOP.Recup                    101234 non-null  str
 16  TOP.Autres.Garanties         101234 non-null  str
dtypes: str(17)
memory usage: 13.1 MB

In [7]:
ressources.head()

,Matricule,Date.presence,Lieu.travail,Population,Site,Type.de.contrat,Duree.travail,Temps.travail,Experience
0,1243,05/01/2021,TELE,CAS,A,CDI,7.333333,100,5783
1,1243,07/01/2021,TELE,CAS,A,CDI,0.883333,100,5784
2,1243,08/01/2021,TELE,CAS,A,CDI,7.333333,100,5785
3,1243,11/01/2021,TELE,CAS,A,CDI,6.95,100,5786
4,1243,12/01/2021,TELE,CAS,A,CDI,7.333333,100,5787

In [8]:
ressources.info()

<class 'pandas.DataFrame'>
RangeIndex: 389353 entries, 0 to 389352
Data columns (total 9 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Matricule        389353 non-null  int64
 1   Date.presence    389353 non-null  str
 2   Lieu.travail     389353 non-null  str
 3   Population       389353 non-null  str
 4   Site             389353 non-null  str
 5   Type.de.contrat  389353 non-null  str
 6   Duree.travail    389353 non-null  str
 7   Temps.travail    389353 non-null  int64
 8   Experience       389353 non-null  int64
dtypes: int64(3), str(6)
memory usage: 26.7 MB

In [9]:
temps.head()

,Numero.dossier,Matricule,Date.debut.traitement,heure.debut.traitement,duree.corrigee
0,5465153,1979,2021/07/03,20:04:14,217.0
1,5465153,1323,2021/07/07,12:29:55,690.0
2,5465153,1735,2021/07/07,14:31:38,297.0
3,5465153,1979,2021/07/03,19:42:12,719.0
4,5465153,706,2021/07/03,18:16:36,44.0

In [10]:
temps.info()

<class 'pandas.DataFrame'>
RangeIndex: 431598 entries, 0 to 431597
Data columns (total 5 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Numero.dossier          431598 non-null  int64
 1   Matricule               431598 non-null  int64
 2   Date.debut.traitement   431598 non-null  str
 3   heure.debut.traitement  431598 non-null  str
 4   duree.corrigee          384127 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 16.5 MB

## 2. Traitement de données

Remarques sur l'état initial des bases données:  
- Les datasets qui viennent d'être importés présentent des incohérences au niveau des format des colonnes (Dtype). Pour la suite de l'analyse, il sera pertienent de changer les formats des colonnes.  Les colonnes de date seront mises sous le bon format date pour permettre de faire des analyses temporelles
- Les mots dans les noms de colonnes sont séparés par des points. Pour éviter des soucis d'erreur de syntaxte python, les points seront remplacés par des tirets  
- Des informations manquent dans certaines cellules. Exemple: Des cellules contiennent '???', ces cellules seront désormais considérées comme des Nan

In [11]:

# 1. Remplacement des points par des tirets du bas dans les noms de colonnes
dossier.columns = dossier.columns.str.replace('.', '_', regex=False)
ressources.columns = ressources.columns.str.replace('.', '_', regex=False)
temps.columns = temps.columns.str.replace('.', '_', regex=False)


# 2. Remplacement des valeurs aberrantes connues par NaN
dossier.replace("???", np.nan, inplace=True)
ressources.replace("???", np.nan, inplace=True)
temps.replace("???", np.nan, inplace=True)

,Numero_dossier,Matricule,Date_debut_traitement,heure_debut_traitement,duree_corrigee
0,5465153,1979,2021/07/03,20:04:14,217.0
1,5465153,1323,2021/07/07,12:29:55,690.0
2,5465153,1735,2021/07/07,14:31:38,297.0
3,5465153,1979,2021/07/03,19:42:12,719.0
4,5465153,706,2021/07/03,18:16:36,44.0
...,...,...,...,...,...
431593,5797870,1364,2022/02/10,11:47:14,17.0
431594,6440976,816,2021/08/03,10:04:09,431.0
431595,7008348,734,2022/12/16,08:44:22,21.0
431596,8401632,1448,2022/08/19,07:08:29,NaN
431597,7929887,222,2022/12/01,22:58:56,99.0

### 2.1. Le DataFrame Dossier

In [12]:
dossier.head()

,Numero_dossier_ID,Client,Formule,date_ouverture,heure_ouverture,Matricule_de_traitement,Cause_intervention,date_de_survenance,Type_d_energie,Outil_d_assistance,Assistance_ou_Administratif,TOP_D_R,TOP_VR,TOP_Rappat_valide,TOP_Poursuite,TOP_Recup,TOP_Autres_Garanties
0,7494402,C5,F99,2021/02/11,10:38:00,326,Panne mécanique,2021/02/11,Diesel,MCS,Assistance,1,0,0,0,0,0
1,7569082,C4,F14,2022/07/12,18:40:00,1164,Panne mécanique,2022/07/12,Essence,MCS,NaN,1,0,0,0,0,0
2,8111190,C0,F1,2021/01/08,12:32:00,1337,Panne mécanique,2021/01/08,Essence,MCS,Assistance,1,1,0,0,0,0
3,5630809,C7,F72,2021/11/08,19:46:00,1322,Panne mécanique,2021/11/08,Essence,MCS,Assistance,1,0,0,0,0,0
4,8179409,C4,F4,2021/08/11,18:12:00,2306,Panne mécanique,2021/08/11,Essence,Higgins,NaN,1,0,0,0,0,0

In [13]:
# 1. Conversion des types pour le DataFrame 'dossier'
dossier['date_de_survenance'] = pd.to_datetime(dossier['date_de_survenance'], format='%Y/%m/%d', errors='coerce')
# Identifiants et indicateurs en entiers
colonnes_numeriques_dossier = [
     'TOP_D_R', 'TOP_VR', 
    'TOP_Rappat_valide', 'TOP_Poursuite', 'TOP_Recup', 'TOP_Autres_Garanties'
]
for col in colonnes_numeriques_dossier:
    dossier[col] = pd.to_numeric(dossier[col], errors='coerce').astype('Int64')

In [14]:
# Fusion de la date et de l'heure pour le DataFrame 'dossier'
# Conversion préalable de date_ouverture en datetime
dossier['date_ouverture'] = pd.to_datetime(dossier['date_ouverture'], format='%Y/%m/%d', errors='coerce')

# Création puis conversion en datetime
combinaison_dossier = dossier['date_ouverture'].dt.strftime('%Y-%m-%d') + ' ' + dossier['heure_ouverture']
dossier['datetime_ouverture'] = pd.to_datetime(combinaison_dossier, format='%Y-%m-%d %H:%M:%S', errors='coerce')

# Suppression des anciennes colonnes devenues redondantes
dossier.drop(columns=['date_ouverture', 'heure_ouverture'], inplace=True)

# Vérification des nouveaux types et aperçu des résultats
print("--- Structure mise à jour pour 'dossier' ---")
print(dossier[['datetime_ouverture']].dtypes)
print(dossier['datetime_ouverture'].head(2))

--- Structure mise à jour pour 'dossier' ---
datetime_ouverture    datetime64[us]
dtype: object
0   2021-02-11 10:38:00
1   2022-07-12 18:40:00
Name: datetime_ouverture, dtype: datetime64[us]

Traitement des doublons et des cellules vides

In [15]:
#  Identification et décompte des doublons parfaits (lignes 100% identiques)
nb_doublons_complets = dossier.duplicated().sum()
print(f"Nombre de lignes doublons (exactes) : {nb_doublons_complets}")

# Identification des doublons sur l'identifiant unique 'Numero_dossier_ID'
nb_doublons_id = dossier.duplicated(subset=['Numero_dossier_ID']).sum()
print(f"Nombre de doublons basés uniquement sur Numero_dossier_ID : {nb_doublons_id}")

# Calcul du pourcentage de valeurs manquantes par colonne
Total_manquants = dossier.isna().sum()
Pourcentage_manquants = (dossier.isna().sum() / len(dossier)) * 100

bilan_manquants = pd.DataFrame({
    'Valeurs Manquantes': Total_manquants,
    'Pourcentage (%)': Pourcentage_manquants
})

print("\n--- Bilan des valeurs manquantes dans 'dossier' ---")
print(bilan_manquants[bilan_manquants['Valeurs Manquantes'] > 0])

Nombre de lignes doublons (exactes) : 840
Nombre de doublons basés uniquement sur Numero_dossier_ID : 1234

--- Bilan des valeurs manquantes dans 'dossier' ---
                             Valeurs Manquantes  Pourcentage (%)
Formule                                    5000         4.939052
date_de_survenance                         1000         0.987810
Assistance_ou_Administratif               10000         9.878104
datetime_ouverture                         1010         0.997689

In [16]:
# Suppression des doublons parfaits (lignes 100% identiques)
dossier.drop_duplicates(inplace=True)
print(f"Dimensions après suppression des doublons parfaits : {dossier.shape}")

Dimensions après suppression des doublons parfaits : (100394, 16)

In [17]:
extraits_doublons = dossier[dossier.duplicated(subset=['Numero_dossier_ID'], keep=False)].sort_values(by='Numero_dossier_ID')

print("\n--- Extrait des dossiers ayant plusieurs lignes distinctes ---")
# Affichage des 6 premières lignes du sous-ensemble pour inspection visuelle
print(extraits_doublons[['Numero_dossier_ID', 'Matricule_de_traitement', 'datetime_ouverture', 'Cause_intervention']].head(6))

--- Extrait des dossiers ayant plusieurs lignes distinctes ---
      Numero_dossier_ID Matricule_de_traitement  datetime_ouverture  \
19873           5476073                     171 2021-01-20 11:34:00
10856           5476073                     171 2021-01-20 11:34:00
57846           5486901                     725 2022-12-28 13:23:00
19307           5486901                     725 2022-12-28 13:23:00
93395           5499899                    1027 2021-04-26 15:20:00
97721           5499899                    1027 2021-04-26 15:20:00

               Cause_intervention
19873             Panne mécanique
10856             Panne mécanique
57846  Clés, Carburant, Crevaison
19307                          NA
93395                      Autres
97721                      Autres

Puisque l'objectif final inclut des modélisations économétriques où chaque observation doit représenter un dossier unique et complet, nous avons juger pertinent de filtrer ces doublons pour ne conserver que la ligne la plus informative (celle contenant le moins de valeurs manquantes) ou, à défaut, la première occurrence.

In [18]:
# Calcul du nombre de valeurs non manquantes par ligne pour prioriser les lignes les plus complètes
dossier['nb_valeurs_reelles'] = dossier.notna().sum(axis=1)

# Tri décroissant selon la complétude, puis conservation de la meilleure ligne pour chaque ID
dossier.sort_values(by='nb_valeurs_reelles', ascending=False, inplace=True)
dossier.drop_duplicates(subset=['Numero_dossier_ID'], keep='first', inplace=True)

# Suppression de la colonne temporaire
dossier.drop(columns=['nb_valeurs_reelles'], inplace=True)


# Imputation des variables catégorielles manquantes par la modalité "Inconnu"
colonnes_categorieles = ['Formule', 'Assistance_ou_Administratif']
for col in colonnes_categorieles:
    dossier[col] = dossier[col].fillna("Inconnu")


# 3. Suppression des observations sans repère temporel valide
dossier.dropna(subset=['date_de_survenance', 'datetime_ouverture'], inplace=True)


# 4. Bilan final du nettoyage de la table dossier
print(f"Dimensions finales du DataFrame 'dossier' : {dossier.shape}")
print("\n--- Décompte final des valeurs manquantes ---")
print(dossier.isna().sum())

Dimensions finales du DataFrame 'dossier' : (98035, 16)

--- Décompte final des valeurs manquantes ---
Numero_dossier_ID              0
Client                         0
Formule                        0
Matricule_de_traitement        0
Cause_intervention             0
date_de_survenance             0
Type_d_energie                 0
Outil_d_assistance             0
Assistance_ou_Administratif    0
TOP_D_R                        0
TOP_VR                         0
TOP_Rappat_valide              0
TOP_Poursuite                  0
TOP_Recup                      0
TOP_Autres_Garanties           0
datetime_ouverture             0
dtype: int64

In [19]:
dossier.info()

<class 'pandas.DataFrame'>
Index: 98035 entries, 101233 to 6306
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Numero_dossier_ID            98035 non-null  str
 1   Client                       98035 non-null  str
 2   Formule                      98035 non-null  str
 3   Matricule_de_traitement      98035 non-null  str
 4   Cause_intervention           98035 non-null  str
 5   date_de_survenance           98035 non-null  datetime64[us]
 6   Type_d_energie               98035 non-null  str
 7   Outil_d_assistance           98035 non-null  str
 8   Assistance_ou_Administratif  98035 non-null  str
 9   TOP_D_R                      98035 non-null  Int64
 10  TOP_VR                       98035 non-null  Int64
 11  TOP_Rappat_valide            98035 non-null  Int64
 12  TOP_Poursuite                98035 non-null  Int64
 13  TOP_Recup                    98035 non-null  Int64
 14  TOP_Autres_Garanties         98035 non-null  Int64
 15  datetime_ouverture           98035 non-null  datetime64[us]
dtypes: Int64(6), datetime64[us](2), str(8)
memory usage: 13.3 MB

### 2.2. Le DataFrame ressources

In [20]:
# 1. Décompte des doublons parfaits (lignes 100% identiques)
nb_doublons_ressources = ressources.duplicated().sum()
print(f"Nombre de lignes doublons (exactes) dans ressources : {nb_doublons_ressources}")

# 2. Vérification de l'unicité du couple Clé Primaire (Matricule + Date_presence)
# Un collaborateur ne devrait idéalement figurer qu'une seule fois par jour de présence
nb_doublons_cle = ressources.duplicated(subset=['Matricule', 'Date_presence']).sum()
print(f"Nombre de doublons sur le couple (Matricule, Date_presence) : {nb_doublons_cle}")

# 3. Décompte et pourcentage de valeurs manquantes par colonne
manquants_ressources = ressources.isna().sum()
pourcentage_ressources = (ressources.isna().sum() / len(ressources)) * 100

bilan_ressources = pd.DataFrame({
    'Valeurs Manquantes': manquants_ressources,
    'Pourcentage (%)': pourcentage_ressources
})

print("\n--- Bilan des valeurs manquantes dans 'ressources' ---")
print(bilan_ressources)

Nombre de lignes doublons (exactes) dans ressources : 0
Nombre de doublons sur le couple (Matricule, Date_presence) : 0

--- Bilan des valeurs manquantes dans 'ressources' ---
                 Valeurs Manquantes  Pourcentage (%)
Matricule                         0              0.0
Date_presence                     0              0.0
Lieu_travail                      0              0.0
Population                        0              0.0
Site                              0              0.0
Type_de_contrat                   0              0.0
Duree_travail                     0              0.0
Temps_travail                     0              0.0
Experience                        0              0.0

Le matricule sera mis en format sting pour matcher avec le marticule de dossier et pour que le modèle ne tente pas de faire des calculs statistiques avec des numéros de matricule

In [21]:
ressources['Matricule'] = ressources['Matricule'].astype(str).str.strip()   
ressources.info()

<class 'pandas.DataFrame'>
RangeIndex: 389353 entries, 0 to 389352
Data columns (total 9 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Matricule        389353 non-null  str
 1   Date_presence    389353 non-null  str
 2   Lieu_travail     389353 non-null  str
 3   Population       389353 non-null  str
 4   Site             389353 non-null  str
 5   Type_de_contrat  389353 non-null  str
 6   Duree_travail    389353 non-null  str
 7   Temps_travail    389353 non-null  int64
 8   Experience       389353 non-null  int64
dtypes: int64(2), str(7)
memory usage: 26.7 MB

Les résultats indiquent que le DataFrame ressources est parfaitement intègre. L'absence de doublons complets, l'unicité du couple clé primaire (Matricule, Date_presence), ainsi que l'inexistance totale de valeurs manquantes permettent de valider directement cette table sans aucune action de nettoyage supplémentaire.

La prochaine étape logique du traitement consiste à analyser et nettoyer la troisième et dernière base de données : temps.

### 2.3. Le DataFrame TEMPS

In [22]:
# 1. Décompte des doublons parfaits (lignes 100% identiques)
nb_doublons_temps = temps.duplicated().sum()
print(f"Nombre de lignes doublons (exactes) dans temps : {nb_doublons_temps}")

# 2. Vérification de la présence de doublons sur la clé d'identification
# Une ligne représente une phase de traitement. Plusieurs lignes peuvent exister pour un même dossier 
# s'il y a eu plusieurs étapes ou plusieurs intervenants (Matricule).
# On vérifie ici si un même collaborateur possède plusieurs entrées identiques pour le même dossier au même instant précis.
nb_doublons_phase = temps.duplicated(subset=[
    'Numero_dossier', 'Matricule', 'Date_debut_traitement', 'heure_debut_traitement'
]).sum()
print(f"Nombre de doublons sur le triplet (Numero_dossier, Matricule, datetime_debut_traitement) : {nb_doublons_phase}")

# 3. Décompte et pourcentage de valeurs manquantes par colonne
manquants_temps = temps.isna().sum()
pourcentage_temps = (temps.isna().sum() / len(temps)) * 100

bilan_temps = pd.DataFrame({
    'Valeurs Manquantes': manquants_temps,
    'Pourcentage (%)': pourcentage_temps
})

print("\n--- Bilan des valeurs manquantes dans 'temps' ---")
print(bilan_temps)

Nombre de lignes doublons (exactes) dans temps : 0
Nombre de doublons sur le triplet (Numero_dossier, Matricule, datetime_debut_traitement) : 0

--- Bilan des valeurs manquantes dans 'temps' ---
                        Valeurs Manquantes  Pourcentage (%)
Numero_dossier                           0         0.000000
Matricule                                0         0.000000
Date_debut_traitement                    0         0.000000
heure_debut_traitement                   0         0.000000
duree_corrigee                       47471        10.998892

In [23]:
# Fusion de la date et de l'heure en un objet datetime complet
temps['datetime_debut_traitement'] = pd.to_datetime(
    temps['Date_debut_traitement'].astype(str) + ' ' + temps['heure_debut_traitement'].astype(str),
    format='%Y/%m/%d %H:%M:%S',
    errors='coerce'
)
temps.drop(columns=['Date_debut_traitement', 'heure_debut_traitement'], inplace=True)

# Nettoyage (duree_corrigee)
temps.dropna(subset=['duree_corrigee'], inplace=True)

# Vérification finale de la structure et des valeurs manquantes de la table 'temps'
print("--- Structure finale du DataFrame 'temps' ---")
print(temps.dtypes)

print("\n--- Décompte final des valeurs manquantes ---")
print(temps.isna().sum())

print(f"\nDimensions finales de la table 'temps' : {temps.shape}")

--- Structure finale du DataFrame 'temps' ---
Numero_dossier                        int64
Matricule                             int64
duree_corrigee                      float64
datetime_debut_traitement    datetime64[us]
dtype: object

--- Décompte final des valeurs manquantes ---
Numero_dossier               0
Matricule                    0
duree_corrigee               0
datetime_debut_traitement    0
dtype: int64

Dimensions finales de la table 'temps' : (384127, 4)

Le numéro de dossier et le numéro de matricule sont transformés en format string pour les futures jointures et une bonne harmonisation.

In [24]:
temps['Numero_dossier'] = temps['Numero_dossier'].astype(str).str.strip()
temps['Matricule'] = temps['Matricule'].astype(str).str.strip()
temps.info()

<class 'pandas.DataFrame'>
Index: 384127 entries, 0 to 431597
Data columns (total 4 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Numero_dossier             384127 non-null  str
 1   Matricule                  384127 non-null  str
 2   duree_corrigee             384127 non-null  float64
 3   datetime_debut_traitement  384127 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(1), str(2)
memory usage: 14.7 MB

In [25]:
temps.head()

  Numero_dossier Matricule  duree_corrigee datetime_debut_traitement
0        5465153      1979           217.0       2021-07-03 20:04:14
1        5465153      1323           690.0       2021-07-07 12:29:55
2        5465153      1735           297.0       2021-07-07 14:31:38
3        5465153      1979           719.0       2021-07-03 19:42:12
4        5465153       706            44.0       2021-07-03 18:16:36

In [26]:
# 1. changement des types de données pour la table 'ressources' et 'temps'
# Ajustement des derniers types dans la table 'ressources'
# Conversion de la date (qui était en JJ/MM/AAAA) pour correspondre au format datetime
ressources['Date_presence'] = pd.to_datetime(ressources['Date_presence'], format='%d/%m/%Y', errors='coerce')
# Conversion de Duree_travail en décimal (float) pour l'économie
ressources['Duree_travail'] = pd.to_numeric(ressources['Duree_travail'], errors='coerce')

# . Préparation de la clé de date dans 'temps'
temps['Date_presence_cle'] = pd.to_datetime(temps['datetime_debut_traitement'].dt.date)

# Pour une jointure parfaite, on s'assure que les deux colonnes de date ont exactement le même type normalisé
temps['Date_presence_cle'] = pd.to_datetime(temps['Date_presence_cle']).dt.normalize()
ressources['Date_presence'] = ressources['Date_presence'].dt.normalize()


# 2. Première fusion : Table 'temps' + Table 'dossier'
df_fusion = pd.merge(
    temps, 
    dossier, 
    left_on='Numero_dossier', 
    right_on='Numero_dossier_ID', 
    how='inner'
)


# 3. Deuxième fusion : Base fusionnée + Table 'ressources'
df_final = pd.merge(
    df_fusion, 
    ressources, 
    left_on=['Matricule', 'Date_presence_cle'], 
    right_on=['Matricule', 'Date_presence'], 
    how='inner'
)


# 4. Nettoyage des colonnes clés devenues redondantes après la jointure
colonnes_a_supprimer = ['Numero_dossier_ID', 'Date_presence_cle', 'Date_presence']
df_final.drop(columns=colonnes_a_supprimer, inplace=True, errors='ignore')


# 5. Exportation du fichier final propre pour un nouveau notebook dédié à la partie économétrie
df_final.to_csv("base_econometrie.csv", index=False)


print(f"Dimensions de la base finale : {df_final.shape}")

Dimensions de la base finale : (366290, 26)